target:
  base_url: "https://api.example.com"
  timeout: 30

log:
  level: "info"
  encoding: "json"
  output: "./logs/pipet.log"

test:
  report_dir: "./reports"
  test_case_dir: "./testcases"
  data_dir: "./sql"

http:
  insecure_skip_verify: true

email:
  from: "768305875@qq.com"
  to: "768305875@qq.com"
  auth_code: "gpfruabgjebubdad"
  smtp_server: "smtp.qq.com"
  smtp_port: 465